# COUNTRIES with Google Street View coverage
# Flag Dictionary of ISO2 UN Country codes

# Available Coverage, manually calibrated values
COUNTRIES = {
    "USA": 1250, "FRA": 250,   "ESP": 500,     # USA,               France,           Spain,
    "TWN": 70,   "SVK": 50,    "POL": 100,     # Taiwan,            Slovakia,         Poland,
    "IRL": 75,   "LVA": 150,   "SGP": 25,      # Ireland,           Latvia,           Singapore,
    "ITA": 100,  "CZE": 100,   "RUS": 2500,    # Italy,             Czechia,          Russia,
    "BGD": 150,  "SMR": 15,    "JPN": 250,     # Bangladesh,        San Marino,       Japan,
    "BRA": 2000, "BGR": 100,   "BLL": 10,      # Brazil,            Bulgaria,         Berlin (DEU),
    "CWN": 10,   "SPO": 10,    "BOO": 10,      # Cape Town (SA),    Sao Paulo (BZ),   Bogota (CO),
    "ATL": 15,   "TOT": 10,    "DET": 15,      # Atlanta (USA),     Toronto (CAN),    Detroit (USA),
    "PJT": 20,   "PXA": 4,     "TKY": 50,      # Pretoria (SA),     Paris (FRA),      Tokyo (JAPAN),
    "TLL": 10,   "AAA": 20,    "MMM": 20,      # Tel-Aviv (IS),     Athens (GRE),     Miami (USA),
    "HST": 20,   "PWJ": 10,    "STD": 15,      # Houston (USA),     Philadelphia(US), Santo Domingo (DR),
    "MSW": 30,   "CBA": 15,    "BNK": 15,      # Moscow (RUS),      Curibitas (BZ),   Bangkok (TH),
    "CGY": 10,   "VVV": 10,    "ANC": 10,      # Calgary (CA),      Vancouver (CA),   Anchorage (USA)
    "SEA": 5,    "BVE": 5,     "SFC": 5,       # Seattle (USA),     Bellevue (USA)    San Francisco (USA),
    "VLA": 2,    "MXC": 10,    "BOV": 2,       # Vladivostok (RU),  Mexico City (MX), Boa Vista (BZ),
    "BUA": 20,   "SOL": 20,    "LUX": 15,      # Buenos Aires (AR), Seoul (SK),       Luxembourg,
    "LON": 10,   "PRE": 5,     "YUL": 10,      # London (UK),       Perth (AUS),      Montreal (QC),
    "YQB": 5,    "NOA": 5,     "GAZ": 5,       # Quebec City (CA),  Nicosia (CY),     Gaziantep (US),
    "DAK": 5,    "CLL": 25,    "DVR": 25,      # Dakar (SN),        Colombo (SK),     Denver (US),
    "DBA": 5,    "MTE": 10,    "PAP": 1000,    # Dubai (UAE),       Mount Everest,    Papeete (PF),
    "NIU": 1000, "NAD": 500,   "SUU": 200,     # Niue,              Nadi (Fiji),      Suva (Fiji),
    "AAT": 200,  "MUA": 10000, "ATU": 2000,    # Chilean Antarctic, MUA Quebec (CA),  Attu Station (US),
    "MKJ": 1500, "BSK": 2000,  "LIE": 2000,    # Mt. Kilomanjaro,   Bishkek (KY),     Liechtenstein,
    "BRB": 2750, "EDM": 5,     "FRO": 4500,    # Barbados,          Edmonton (CA),    Faroe Islands,
    "CUH": 2000, "LAK": 9000,  "PYP": 6000,    # Churchill (CA),    Ladakh (IN/PK),   Pyongyang (NK),
    "GGD": 3500, "PMM": 1000,  "YUK": 100,     # Gorkha (NP),       St. Pierre (FR),  Yakutsk (RU),
    "IST": 10,   "SAH": 5000,  "PII": 100,     # Istanbul (TY),     North Algeria,    Adamstown (PI),
    "MHH": 2000, "MHG": 300,   "REU": 2500,    # Ebeye (MIUS),      Ebadon (MIUS),    Reunion (FR),
    "IOY": 900,  "PAL": 6000,  "MDY": 1000,    # BOIT (UK),         Palau,            Midway Atoll (US),
    "NYC": 5,    "AGQ": 4500,  "TGQ": 250000,  # New York (US),     Algonquin (CA),   Torngat Natl Park (CA),
    "RST": 5000, "AIK": 7000,  "SAK": 10000,   # Resolute (CA),     Alavik (CA),      Sanikiluaq (CA),
    "KAK": 5000, "CHE": 50,    "AQA": 10000,   # Kamchatka (RU),    Switzerland,      Base Yelcho (AQ),
    "MLT": 50,   "AUK": 10,    "BNN": 10000,   # Malta,             Auckland (NZ)     Bhutan,
    "IIK": 900,  "DVN": 3000,  "SUY": 2500,    # Innukjuak (CA),    Devon Isl. (CA),  Sulaymaniyah (IQ).
    "BRR": 1400, "QNP": 10000, "DNK": 4000,    # Bahrain,           Quinnipac (CA),   Denmark,
    "LOM": 2000, "FTW": 2000,  "MYT": 4200,    # Lome (Togo)        Freetown (SL),    Mayotte (France)
    "NUM": 1500, "IRR": 4000,  "TUS": 2000,              # Noumea (NC FRsg),
    "ESH": 200000, "WTH": 500
}

FLAG_DICTIONARY = {
    "AD": "🇦🇩", "AE": "🇦🇪", "AF": "🇦🇫", "AG": "🇦🇬", "AI": "🇦🇮", "AL": "🇦🇱", "AM": "🇦🇲", "AO": "🇦🇴",
    "AQ": "🇦🇶", "AR": "🇦🇷", "AS": "🇦🇸", "AT": "🇦🇹", "AU": "🇦🇺", "AW": "🇦🇼", "AX": "🇦🇽", "AZ": "🇦🇿",
    "BA": "🇧🇦", "BB": "🇧🇧", "BD": "🇧🇩", "BE": "🇧🇪", "BF": "🇧🇫", "BG": "🇧🇬", "BH": "🇧🇭", "BI": "🇧🇮",
    "BJ": "🇧🇯", "BL": "🇧🇱", "BM": "🇧🇲", "BN": "🇧🇳", "BO": "🇧🇴", "BQ": "🇧🇶", "BR": "🇧🇷", "BS": "🇧🇸",
    "BT": "🇧🇹", "BV": "🇧🇻", "BW": "🇧🇼", "BY": "🇧🇾", "BZ": "🇧🇿", "CA": "🇨🇦", "CC": "🇨🇨", "CD": "🇨🇩",
    "CF": "🇨🇫", "CG": "🇨🇬", "CH": "🇨🇭", "CI": "🇨🇮", "CK": "🇨🇰", "CL": "🇨🇱", "CM": "🇨🇲", "CN": "🇨🇳",
    "CO": "🇨🇴", "CR": "🇨🇷", "CU": "🇨🇺", "CV": "🇨🇻", "CW": "🇨🇼", "CX": "🇨🇽", "CY": "🇨🇾", "CZ": "🇨🇿",
    "DE": "🇩🇪", "DJ": "🇩🇯", "DK": "🇩🇰", "DM": "🇩🇲", "DO": "🇩🇴", "DZ": "🇩🇿", "EC": "🇪🇨", "EE": "🇪🇪",
    "EG": "🇪🇬", "EH": "🇪🇭", "ER": "🇪🇷", "ES": "🇪🇸", "ET": "🇪🇹", "FI": "🇫🇮", "FJ": "🇫🇯", "FK": "🇫🇰",
    "FM": "🇫🇲", "FO": "🇫🇴", "FR": "🇫🇷", "GA": "🇬🇦", "GB": "🇬🇧", "GD": "🇬🇩", "GE": "🇬🇪", "GF": "🇬🇫",
    "GG": "🇬🇬", "GH": "🇬🇭", "GI": "🇬🇮", "GL": "🇬🇱", "GM": "🇬🇲", "GN": "🇬🇳", "GP": "🇬🇵", "GQ": "🇬🇶",
    "GR": "🇬🇷", "GS": "🇬🇸", "GT": "🇬🇹", "GU": "🇬🇺", "GW": "🇬🇼", "GY": "🇬🇾", "HK": "🇭🇰", "HM": "🇭🇲",
    "HN": "🇭🇳", "HR": "🇭🇷", "HT": "🇭🇹", "HU": "🇭🇺", "ID": "🇮🇩", "IE": "🇮🇪", "IL": "🇮🇱", "IM": "🇮🇲",
    "IN": "🇮🇳", "IO": "🇮🇴", "IQ": "🇮🇶", "IR": "🇮🇷", "IS": "🇮🇸", "IT": "🇮🇹", "JE": "🇯🇪", "JM": "🇯🇲",
    "JO": "🇯🇴", "JP": "🇯🇵", "KE": "🇰🇪", "KG": "🇰🇬", "KH": "🇰🇭", "KI": "🇰🇮", "KM": "🇰🇲", "KN": "🇰🇳",
    "KP": "🇰🇵", "KR": "🇰🇷", "KW": "🇰🇼", "KY": "🇰🇾", "KZ": "🇰🇿", "LA": "🇱🇦", "LB": "🇱🇧", "LC": "🇱🇨",
    "LI": "🇱🇮", "LK": "🇱🇰", "LR": "🇱🇷", "LS": "🇱🇸", "LT": "🇱🇹", "LU": "🇱🇺", "LV": "🇱🇻", "LY": "🇱🇾",
    "MA": "🇲🇦", "MC": "🇲🇨", "MD": "🇲🇩", "ME": "🇲🇪", "MF": "🇲🇫", "MG": "🇲🇬", "MH": "🇲🇭", "MK": "🇲🇰",
    "ML": "🇲🇱", "MM": "🇲🇲", "MN": "🇲🇳", "MO": "🇲🇴", "MP": "🇲🇵", "MQ": "🇲🇶", "MR": "🇲🇷", "MS": "🇲🇸",
    "MT": "🇲🇹", "MU": "🇲🇺", "MV": "🇲🇻", "MW": "🇲🇼", "MX": "🇲🇽", "MY": "🇲🇾", "MZ": "🇲🇿", "NA": "🇳🇦",
    "NC": "🇳🇨", "NE": "🇳🇪", "NF": "🇳🇫", "NG": "🇳🇬", "NI": "🇳🇮", "NL": "🇳🇱", "NO": "🇳🇴", "NP": "🇳🇵",
    "NR": "🇳🇷", "NU": "🇳🇺", "NZ": "🇳🇿", "OM": "🇴🇲", "PA": "🇵🇦", "PE": "🇵🇪", "PF": "🇵🇫", "PG": "🇵🇬",
    "PH": "🇵🇭", "PK": "🇵🇰", "PL": "🇵🇱", "PM": "🇵🇲", "PN": "🇵🇳", "PR": "🇵🇷", "PS": "🇵🇸", "PT": "🇵🇹",
    "PW": "🇵🇼", "PY": "🇵🇾", "QA": "🇶🇦", "RE": "🇷🇪", "RO": "🇷🇴", "RS": "🇷🇸", "RU": "🇷🇺", "RW": "🇷🇼",
    "SA": "🇸🇦", "SB": "🇸🇧", "SC": "🇸🇨", "SD": "🇸🇩", "SE": "🇸🇪", "SG": "🇸🇬", "SH": "🇸🇭", "SI": "🇸🇮",
    "SJ": "🇸🇯", "SK": "🇸🇰", "SL": "🇸🇱", "SM": "🇸🇲", "SN": "🇸🇳", "SO": "🇸🇴", "SR": "🇸🇷", "SS": "🇸🇸",
    "ST": "🇸🇹", "SV": "🇸🇻", "SX": "🇸🇽", "SY": "🇸🇾", "SZ": "🇸🇿", "TC": "🇹🇨", "TD": "🇹🇩", "TF": "🇹🇫",
    "TG": "🇹🇬", "TH": "🇹🇭", "TJ": "🇹🇯", "TK": "🇹🇰", "TL": "🇹🇱", "TM": "🇹🇲", "TN": "🇹🇳", "TO": "🇹🇴",
    "TR": "🇹🇷", "TT": "🇹🇹", "TV": "🇹🇻", "TW": "🇹🇼", "TZ": "🇹🇿", "UA": "🇺🇦", "UG": "🇺🇬", "UM": "🇺🇲",
    "US": "🇺🇸", "UY": "🇺🇾", "UZ": "🇺🇿", "VA": "🇻🇦", "VC": "🇻🇨", "VE": "🇻🇪", "VG": "🇻🇬", "VI": "🇻🇮",
    "VN": "🇻🇳", "VU": "🇻🇺", "WF": "🇼🇫", "WS": "🇼🇸", "YE": "🇾🇪", "YT": "🇾🇹", "ZA": "🇿🇦", "ZM": "🇿🇲",
    "ZW": "🇿🇼", "LD": "🏳️"
    }
