# Countries with Google Street View coverage

countries_codes = {
    "iso3": (
        "BLL", #berlin
        "CWN",
        "SPO",
        "BOO",
        "ATL",
        "TOT",
        "DET",
        "PJT",
        "PXA",
        "TKY",
        "TLL",
        "AAA",
        "MMM",
        "HST",
        "PWJ",
        "STD",
        "MSW",
        "CBA",
        # Antarctica
        "ATA",
        # South America
        "ARG",
        "BRA",
        "BOL",
        "CHL",
        "COL",
        "ECU",
        "FLK",
        "PER",
        "PRY",
        "SGS",
        "URY",
        # Central America
        "BMU",
        "CRI",
        # 'CUW',
        "DOM",
        "GTM",
        "MEX",
        "MTQ",
        "PRI",
        "VIR",
        # North America
        "CAN",
        "USA",
        "SPM",
        # Oceania
        "ASM",
        "AUS",
        "CCK",
        "CXR",
        "GUM",
        "MNP",
        # 'PCK',
        "VUT",
        # Africa
        "BWA",
        "EGY",
        "GHA",
        "KEN",
        "LSO",
        "MDG",
        "NGA",
        "REU",
        "RWA",
        "SEN",
        "SWZ",
        "TUN",
        "TZA",
        "UGA",
        "ZAF",
        # Europe
        "ALA",
        "ALB",
        "AND",
        "AUT",
        "BEL",
        "BGR",
        "BLR",
        "CHE",
        "CZE",
        "DEU",
        "DNK",
        "ESP",
        "EST",
        "FIN",
        "FRA",
        "GBR",
        "GIB",
        "GRC",
        "GRL",
        "HRV",
        "HUN",
        "IMN",
        "IRL",
        "ISL",
        "ITA",
        "JEY",
        "LTU",
        "LUX",
        "LVA",
        "MCO",
        "MKD",
        "MLT",
        "MNE",
        "NLD",
        "NOR",
        "POL",
        "PRT",
        "ROU",
        "SJM",
        "SMR",
        "SRB",
        "SVK",
        "SVN",
        "SWE",
        "TUR",
        "VAT",
        "UKR",
        # Asia
        "ARE",
        "BGD",
        "BTN",
        "CHN",
        "HKG",
        "IDN",
        "IND",
        "IOT",
        "IRQ",
        "ISR",
        "JOR",
        "JPN",
        "KGZ",
        "KHM",
        "KOR",
        "LAO",
        "LBN",
        "LKA",
        "MNG",
        "MYS",
        "NPL",
        "PAK",
        "PHL",
        "PSE",
        "QAT",
        "RUS",
        "SGP",
        "THA",
        "TWN",
        "VNM",
    )
}